version: 2

sources:
  - name: saas_metrics
    schema: main
    tables:
      - name: dates
      - name: revenue_changes
      - name: revenue_starting_balance
      - name: revenue_types
      - name: value_types
      - name: customer_count
      - name: mrr_view
      - name: pnl
      - name: gl_accounts
      - name: gl_accounts_types
